### ISSUE TITLE
Git LFS issue

### ISSUE THREAD

**Issue by ph4z** [bleszerd/Brave_BAT_Bot#1]
Hello,

It is actually not possible to download the brave and the instance datas because your git LFS repo don't have enought bandwith.

How can I grab these datas ? 
Does your brave instance is required ? Will it work with a standard brave instance ?

KR.

**Comment by bleszerd** [comment]
Sorry, I ended up not considering the lfs limit. You can try to do:

* Fork this repository
* Go to settings -> options and check "Include Git LFS objects in files" in the Files section.
* Download the forked repository through your browser.

Thanks for reporting this issue.

**Comment by bleszerd** [comment]
Sorry, I ended up not considering the lfs limit. You can try to do:

* Fork this repository
* Go to settings -> options and check "Include Git LFS objects in files" in the Files section.
* Download the forked repository through your browser

Thanks for reporting this issue.
