### ISSUE TITLE
Wallet link

### ISSUE THREAD

**Issue by HowWhat42** [bleszerd/Brave_BAT_Bot#2]
Hello,

Is there a way to directly link the uphold wallet with the different instances to automatically get the transfer ?
Or do you have any other way to recover the collected BAT ?

Also another point, is it possible to use the headless function of pupeteer and still earn BAT ? Because if it's possible it would probably lower the CPU and RAM usage.

PS: Thanks for the project it is awesome !

**Comment by bleszerd** [comment]
Withdraw methods are browser defaults, you will have to manually transfer all workers when you reach at least the minimum required by Brave. 

Unfortunately headless mode doesn't work for ads on the homepage as there's no way to navigate to it (or settings like page) without an X server, but I can try with another page where ads can also appear.
Feel free to open more issues or pull requests if you have an idea!
